### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by calclavia** [auth0/Lock-Facebook.Android#11]
Following this guide: https://auth0.com/docs/quickstart/native/react-native-android

Using React Native v0.33

build.gradle:
```
    compile ('com.auth0.android:lock-facebook:2.3.+') {
        exclude group: 'com.parse.bolts', module: 'bolts-tasks'
        exclude group: 'com.parse.bolts', module: 'bolts-applinks'
    }
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
```

Received the follow error upon `react-native run-android`
```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;
Unknown source file :  	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :  	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :  	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :  	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :  	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :  	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :  	at com.android.dx.command.Main.main(Main.java:106)
```

Tried solutions from:
http://stackoverflow.com/questions/35138908/unable-to-execute-dex-multiple-dex-files-define-lbolts-aggregateexception
http://stackoverflow.com/questions/27694355/unable-to-execute-dex-multiple-dex-files-define-lbolts-aggregateexception

**Comment by hzalaz** [comment]
Not sure what we can do about it since its a dependency of facebook SDK and not ours. In theory the exclude should fix that but I think you have the wrong package and/or artifactId for bolts lib
